# Stage 1: Build the application
FROM maven:latest AS build

# Maintainer info
LABEL maintainer="Sunny <sunny@example.com>"

# Set the working directory
WORKDIR /app

# Clone the Git repository into the container
RUN git clone https://github.com/Sunny-jsg/Docker-App.git .
 

# Build the application (skip tests for faster build)
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:18-jdk-alpine

# Maintainer info
LABEL maintainer="Sunny <sunny@example.com>"

# Set the working directory
WORKDIR /app

# Copy the built jar file from the build stage
COPY --from=build /app/01-Docker-App/target/*.jar app.jar

# Expose the port the app runs on (default Spring Boot port)
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
